import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { addCliCommand, addCommand, type AddManyResult } from "../commands/add";
import { statusCommand } from "../commands/status";
import { loadManifest } from "../core/manifest";
import { sha256 } from "../core/hash";
import { cleanupTempDirs, git, initUpstream, makeProject, writeFiles } from "./helpers";

afterAll(cleanupTempDirs);

describe("regraft add", () => {
  it("vendors a directory, records the source, and sets up the workdir", () => {
    const up = initUpstream({ "lib/a.ts": "export const a = 1;\n", "lib/sub/b.ts": "export const b = 2;\n" });
    const project = makeProject();

    const result = addCommand(`${up.url}#main:lib`, "vendor/lib", { cwd: project });
    expect(result.exitCode).toBe(0);
    expect(result.alreadyTracked).toBe(false);
    expect(result.written.sort()).toEqual(["vendor/lib/a.ts", "vendor/lib/sub/b.ts"]);
    expect(readFileSync(join(project, "vendor/lib/a.ts"), "utf8")).toBe("export const a = 1;\n");

    const manifest = loadManifest(project)!;
    expect(manifest.sources).toHaveLength(1);
    const source = manifest.sources[0]!;
    expect(source).toMatchObject({ url: up.url, remoteRef: "main", path: "lib", dest: "vendor/lib", pinnedSha: up.sha });
    expect(source.files["a.ts"]).toBe(sha256("export const a = 1;\n"));
    expect(source.files["sub/b.ts"]).toBe(sha256("export const b = 2;\n"));
    expect(source.unresolved).toEqual([]);

    expect(readFileSync(join(project, ".regraft/.gitignore"), "utf8")).toBe("*\n");
    expect(readFileSync(join(project, "PATCH.md"), "utf8")).toContain("Generated by regraft");
  });

  it("vendors a single file with relPath '' keyed to dest", () => {
    const up = initUpstream({ "src/utils.ts": "export const util = true;\n" });
    const project = makeProject();

    const result = addCommand(`${up.url}#main:src/utils.ts`, "lib/utils.ts", { cwd: project });
    expect(result.exitCode).toBe(0);
    expect(result.written).toEqual(["lib/utils.ts"]);
    expect(readFileSync(join(project, "lib/utils.ts"), "utf8")).toBe("export const util = true;\n");

    const source = loadManifest(project)!.sources[0]!;
    expect(source.dest).toBe("lib/utils.ts");
    expect(Object.keys(source.files)).toEqual([""]);
  });

  it("defaults dest to the basename of the upstream path", () => {
    const up = initUpstream({ "packages/core/index.ts": "core\n" });
    const project = makeProject();
    const result = addCommand(`${up.url}#main:packages/core`, undefined, { cwd: project });
    expect(result.source.dest).toBe("core");
    expect(existsSync(join(project, "core/index.ts"))).toBe(true);
  });

  it("resolves the default branch when no ref is given", () => {
    const up = initUpstream({ "a.txt": "x\n" });
    const project = makeProject();
    const result = addCommand(up.url, "vendored", { cwd: project });
    expect(result.source.remoteRef).toBe("main");
    expect(result.source.pinnedSha).toBe(up.sha);
  });

  it("tracks identical existing files silently and skips differing ones", () => {
    const up = initUpstream({ "lib/same.ts": "same\n", "lib/diff.ts": "upstream\n" });
    const project = makeProject();
    writeFiles(project, { "vendor/same.ts": "same\n", "vendor/diff.ts": "mine, precious\n" });

    const result = addCommand(`${up.url}#main:lib`, "vendor", { cwd: project });
    expect(result.exitCode).toBe(1); // skips surface loudly
    expect(result.identical).toEqual(["vendor/same.ts"]);
    expect(result.skipped).toHaveLength(1);
    expect(result.skipped[0]).toMatchObject({ path: "vendor/diff.ts" });
    expect(result.skipped[0]!.reason).toContain("--force");
    // untouched:
    expect(readFileSync(join(project, "vendor/diff.ts"), "utf8")).toBe("mine, precious\n");
    // tracked map only contains what was written or identical
    const source = loadManifest(project)!.sources[0]!;
    expect(Object.keys(source.files).sort()).toEqual(["same.ts"]);
  });

  it("--force overwrites differing files", () => {
    const up = initUpstream({ "lib/diff.ts": "upstream\n" });
    const project = makeProject();
    writeFiles(project, { "vendor/diff.ts": "mine\n" });

    const result = addCommand(`${up.url}#main:lib`, "vendor", { cwd: project, force: true });
    expect(result.exitCode).toBe(0);
    expect(result.written).toEqual(["vendor/diff.ts"]);
    expect(readFileSync(join(project, "vendor/diff.ts"), "utf8")).toBe("upstream\n");
  });

  it("--dry-run writes nothing at all", () => {
    const up = initUpstream({ "lib/a.ts": "a\n" });
    const project = makeProject();

    const result = addCommand(`${up.url}#main:lib`, "vendor", { cwd: project, dryRun: true });
    expect(result.dryRun).toBe(true);
    expect(result.written).toEqual(["vendor/a.ts"]);
    expect(existsSync(join(project, "vendor"))).toBe(false);
    expect(loadManifest(project)).toBeNull();
    expect(existsSync(join(project, "PATCH.md"))).toBe(false);
  });

  it("is idempotent: re-adding the same source is an explicit no-op", () => {
    const up = initUpstream({ "lib/a.ts": "a\n" });
    const project = makeProject();
    addCommand(`${up.url}#main:lib`, "vendor", { cwd: project });

    const again = addCommand(`${up.url}#main:lib`, "vendor", { cwd: project });
    expect(again.exitCode).toBe(0);
    expect(again.alreadyTracked).toBe(true);
    expect(again.written).toEqual([]);
    expect(loadManifest(project)!.sources).toHaveLength(1);
  });

  it("errors when the upstream path does not exist", () => {
    const up = initUpstream({ "lib/a.ts": "a\n" });
    const project = makeProject();
    expect(() => addCommand(`${up.url}#main:no/such/dir`, "vendor", { cwd: project })).toThrow(/does not exist/);
  });

  it("returns a stable --json shape", () => {
    const up = initUpstream({ "lib/a.ts": "a\n" });
    const project = makeProject();
    const result = addCommand(`${up.url}#main:lib`, "vendor", { cwd: project });
    expect(Object.keys(result).sort()).toEqual(
      ["adopted", "alreadyTracked", "command", "dryRun", "exitCode", "identical", "skipped", "source", "written"].sort(),
    );
    expect(Object.keys(result.source).sort()).toEqual(["dest", "path", "pinnedSha", "remoteRef", "url"].sort());
  });

  it("--adopt tracks existing differing files as local modifications without touching disk", () => {
    const up = initUpstream({ "lib/theme.ts": "upstream tokens\n", "lib/util.ts": "util\n" });
    const project = makeProject();
    writeFiles(project, { "vendor/theme.ts": "my brand tokens\n" });

    const result = addCommand(`${up.url}#main:lib`, "vendor", { cwd: project, adopt: true });
    expect(result.exitCode).toBe(0);
    expect(result.adopted).toEqual(["vendor/theme.ts"]);
    expect(result.written).toEqual(["vendor/util.ts"]);
    expect(result.skipped).toEqual([]);
    // disk untouched:
    expect(readFileSync(join(project, "vendor/theme.ts"), "utf8")).toBe("my brand tokens\n");
    // baseline is the upstream content, so the file classifies as modified:
    const source = loadManifest(project)!.sources[0]!;
    expect(source.files["theme.ts"]).toBe(sha256("upstream tokens\n"));
    const status = statusCommand({ cwd: project, offline: true });
    const file = status.sources[0]!.files.find((f) => f.path === "vendor/theme.ts");
    expect(file!.status).toBe("modified-unrecorded");
  });

  it("rejects --force together with --adopt", () => {
    const up = initUpstream({ "lib/a.ts": "a\n" });
    const project = makeProject();
    expect(() => addCommand(`${up.url}#main:lib`, "vendor", { cwd: project, force: true, adopt: true })).toThrow(
      /mutually exclusive/,
    );
  });

  it("tracks a PR head (refs/pull/N/head) as a live ref", () => {
    const up = initUpstream({ "lib/a.ts": "pr content\n" });
    git(up.dir, "update-ref", "refs/pull/1/head", up.sha);
    const project = makeProject();

    const result = addCommand(`${up.url}#pull/1/head:lib`, "vendor", { cwd: project });
    expect(result.exitCode).toBe(0);
    expect(result.source.remoteRef).toBe("pull/1/head");
    expect(result.source.pinnedSha).toBe(up.sha);
    expect(readFileSync(join(project, "vendor/a.ts"), "utf8")).toBe("pr content\n");
  });
});

describe("regraft add (CLI arg handling)", () => {
  it("treats a trailing plain path as the dest for a single source", () => {
    const up = initUpstream({ "lib/a.ts": "a\n" });
    const project = makeProject();
    const result = addCliCommand([`${up.url}#main:lib`, "vendor/here"], { cwd: project });
    expect("results" in result).toBe(false);
    expect(existsSync(join(project, "vendor/here/a.ts"))).toBe(true);
  });

  it("adds several sources in one call, each to its default dest", () => {
    const upA = initUpstream({ "liba/a.ts": "a\n" });
    const upB = initUpstream({ "libb/b.ts": "b\n" });
    const project = makeProject();

    const result = addCliCommand([`${upA.url}#main:liba`, `${upB.url}#main:libb`], { cwd: project }) as AddManyResult;
    expect(result.results).toHaveLength(2);
    expect(result.exitCode).toBe(0);
    expect(existsSync(join(project, "liba/a.ts"))).toBe(true);
    expect(existsSync(join(project, "libb/b.ts"))).toBe(true);
    expect(loadManifest(project)!.sources).toHaveLength(2);
  });

  it("rejects a dest alongside multiple sources", () => {
    const project = makeProject();
    expect(() => addCliCommand(["a/b/tree/main/x", "c/d/tree/main/y", "vendor/lib"], { cwd: project })).toThrow(
      /only supported with a single source/,
    );
  });

  it("propagates exit code 1 when any source skips files", () => {
    const upA = initUpstream({ "liba/a.ts": "a\n" });
    const upB = initUpstream({ "libb/b.ts": "upstream\n" });
    const project = makeProject();
    writeFiles(project, { "libb/b.ts": "mine\n" });

    const result = addCliCommand([`${upA.url}#main:liba`, `${upB.url}#main:libb`], { cwd: project }) as AddManyResult;
    expect(result.exitCode).toBe(1);
    expect(result.results[0]!.exitCode).toBe(0);
    expect(result.results[1]!.exitCode).toBe(1);
  });
});
