import { describe, expect, it } from "vitest";
import { renderPatchMd } from "../core/patchmd";
import type { Manifest } from "../core/manifest";

const SHA = "c".repeat(40);
const HASH = "d".repeat(64);

function manifestWith(intentFiles: Record<string, string>, trackedRels: string[]): Manifest {
  const id = "g_0123456789abcdef";
  return {
    version: 2,
    grafts: [
      {
        id,
        name: "lib",
        url: "https://github.com/acme/widgets.git",
        remoteRef: "main",
        path: "",
        dest: "lib",
        pinnedSha: SHA,
        ownership: "complete",
        excluded: [],
        files: Object.fromEntries(
          trackedRels.map((rel) => [
            rel,
            {
              upstreamHash: HASH,
              localHash: HASH,
              intentIds: intentFiles[`lib/${rel}`] ? ["feedbeef"] : [],
              needsIntent: false,
              pending: null,
            },
          ]),
        ),
      },
    ],
    intents: [
      {
        id: "feedbeef",
        date: "2026-03-04T10:00:00.000Z",
        description: "Swapped icons for brand set.",
        targets: Object.entries(intentFiles).map(([path, hash]) =>
          path.startsWith("lib/")
            ? { kind: "graft-file" as const, graftId: id, rel: path.slice(4), path, hash }
            : { kind: "legacy-orphan" as const, path, hash },
        ),
      },
    ],
  };
}

describe("renderPatchMd", () => {
  it("includes a tool-managed header explaining the file", () => {
    const md = renderPatchMd({ version: 2, grafts: [], intents: [] });
    expect(md).toContain("Generated by regraft");
    expect(md).toContain("records why Grafts");
    expect(md).toContain("No notes recorded yet");
  });

  it("renders one section per intent with date, files, and description", () => {
    const md = renderPatchMd(manifestWith({ "lib/icons.ts": HASH }, ["icons.ts"]));
    expect(md).toContain("## 2026-03-04 — feedbeef");
    expect(md).toContain("`lib/icons.ts`");
    expect(md).toContain("Swapped icons for brand set.");
    expect(md).not.toContain("(orphaned");
  });

  it("marks intents orphaned when none of their files are tracked anymore", () => {
    const md = renderPatchMd(manifestWith({ "gone/icons.ts": HASH }, ["icons.ts"]));
    expect(md).toContain("(orphaned — files no longer tracked)");
  });

  it("keeps intents non-orphaned if at least one file is still tracked", () => {
    const md = renderPatchMd(manifestWith({ "lib/icons.ts": HASH, "gone/other.ts": HASH }, ["icons.ts"]));
    expect(md).not.toContain("orphaned —");
    expect(md).toContain("*(inactive or untracked)*");
  });
});
