import { rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { renderBrief, writeBrief, type BriefSection, type BriefWarning } from "../core/brief";
import { findUnrecordedModifications } from "../core/classify";
import {
  ensureCacheRepo,
  ensureCommit,
  ensureGitAvailable,
  ensureHead,
  listFilesAt,
  logRange,
  readFileAt,
  resolveRemote,
} from "../core/git";
import { isBinary, readFileIfExists, sha256 } from "../core/hash";
import { requireManifest, saveManifest, type Source } from "../core/manifest";
import { mergeThreeWay } from "../core/merge";
import { writePatchMd } from "../core/patchmd";
import {
  cacheRoot,
  findRoot,
  projectPath,
  pruneEmptyDirs,
  upstreamPath,
  writeFileEnsuringDir,
} from "../core/workspace";

export interface PullOptions {
  cwd: string;
  dryRun?: boolean;
  force?: boolean;
}

export interface PullSourceResult {
  url: string;
  remoteRef: string;
  dest: string;
  oldSha: string;
  newSha: string;
  upToDate: boolean;
  /** New upstream files now tracked (written unless identical on disk). */
  added: string[];
  /** Locally unmodified files updated (or already matching) upstream. */
  fastForwarded: string[];
  /** Locally modified files merged cleanly with upstream changes. */
  merged: string[];
  /** Conflicting files overwritten with upstream content via --force. */
  forced: string[];
  /** Files deleted locally to match upstream deletions. */
  deleted: string[];
  /** Files with fresh diff3 conflict markers written in place. */
  conflicts: string[];
  skipped: { path: string; reason: string }[];
  warnings: { path: string; message: string }[];
}

export interface PullResult {
  command: "pull";
  exitCode: 0 | 1;
  dryRun: boolean;
  /** True when any file received conflict markers this pull. */
  conflicts: boolean;
  /** Project-relative path of the reconciliation brief, or null. */
  brief: string | null;
  /**
   * Tracked files that were modified locally without a recorded intent at the
   * time of this pull (a heads-up, never a failure: briefs can only include
   * intent context that was recorded).
   */
  unrecordedModifications: string[];
  sources: PullSourceResult[];
}

interface PullCtx {
  dryRun: boolean;
  force: boolean;
}

export function pullCommand(opts: PullOptions): PullResult {
  ensureGitAvailable();
  const root = findRoot(opts.cwd);
  const manifest = requireManifest(root);
  const ctx: PullCtx = { dryRun: opts.dryRun ?? false, force: opts.force ?? false };

  // Snapshot BEFORE merging: these are the local edits whose "why" is not on
  // record, so a brief generated by this pull cannot explain them.
  const unrecordedModifications = findUnrecordedModifications(root, manifest);

  const sources: PullSourceResult[] = [];
  const briefSections: BriefSection[] = [];

  for (const source of manifest.sources) {
    const head = resolveRemote(source.url, source.remoteRef);
    if (head.sha === source.pinnedSha) {
      sources.push({
        url: source.url,
        remoteRef: source.remoteRef,
        dest: source.dest,
        oldSha: source.pinnedSha,
        newSha: source.pinnedSha,
        upToDate: true,
        added: [],
        fastForwarded: [],
        merged: [],
        forced: [],
        deleted: [],
        conflicts: [],
        skipped: [],
        warnings: [],
      });
      continue;
    }

    const cache = ensureCacheRepo(cacheRoot(root), source.url);
    const newSha = ensureHead(cache, source.url, head);
    ensureCommit(cache, source.url, source.pinnedSha, source.remoteRef);

    const result = pullSource(root, cache, source, newSha, ctx);
    sources.push(result);

    if (result.conflicts.length > 0 || result.warnings.length > 0) {
      briefSections.push({
        url: source.url,
        remoteRef: source.remoteRef,
        oldSha: source.pinnedSha,
        newSha,
        conflicts: result.conflicts,
        warnings: result.warnings as BriefWarning[],
        log: logRange(cache, source.pinnedSha, newSha, source.path),
      });
    }

    if (!ctx.dryRun) source.pinnedSha = newSha;
  }

  let briefPath: string | null = null;
  if (briefSections.length > 0 && !ctx.dryRun) {
    const now = new Date();
    briefPath = writeBrief(root, renderBrief(briefSections, manifest.intents, now), now);
  }

  if (!ctx.dryRun) {
    saveManifest(root, manifest);
    writePatchMd(root, manifest);
  }

  const anyConflict = sources.some((s) => s.conflicts.length > 0);
  const anyWarning = sources.some((s) => s.warnings.length > 0);
  return {
    command: "pull",
    exitCode: anyConflict || anyWarning ? 1 : 0,
    dryRun: ctx.dryRun,
    conflicts: anyConflict,
    brief: briefPath,
    unrecordedModifications,
    sources,
  };
}

function pullSource(root: string, cache: string, source: Source, newSha: string, ctx: PullCtx): PullSourceResult {
  const oldSha = source.pinnedSha;
  const newList = listFilesAt(cache, newSha, source.path);
  const oldSet = new Set(listFilesAt(cache, oldSha, source.path));
  const newSet = new Set(newList);
  const rels = [...new Set([...Object.keys(source.files), ...newList])].sort();

  const result: PullSourceResult = {
    url: source.url,
    remoteRef: source.remoteRef,
    dest: source.dest,
    oldSha,
    newSha,
    upToDate: false,
    added: [],
    fastForwarded: [],
    merged: [],
    forced: [],
    deleted: [],
    conflicts: [],
    skipped: [],
    warnings: [],
  };

  for (const rel of rels) {
    const proj = projectPath(source.dest, rel);
    const abs = join(root, proj);
    const stored = source.files[rel];
    const diskBuf = readFileIfExists(abs);
    const diskHash = diskBuf === null ? null : sha256(diskBuf);
    const inNew = newSet.has(rel);
    const newBuf = inNew ? readFileAt(cache, newSha, upstreamPath(source.path, rel)) : null;
    const newHash = newBuf === null ? null : sha256(newBuf);

    // Unresolved conflicts from a previous pull are skipped until resolved,
    // so markers never stack.
    if (source.unresolved.includes(rel)) {
      result.skipped.push({ path: proj, reason: "unresolved conflict from a previous pull; run `regraft resolve` first" });
      continue;
    }

    if (stored === undefined) {
      // File is new upstream (not tracked yet).
      if (newBuf === null || newHash === null) continue;
      if (diskHash === null) {
        if (!ctx.dryRun) {
          writeFileEnsuringDir(abs, newBuf);
          source.files[rel] = newHash;
        }
        result.added.push(proj);
      } else if (diskHash === newHash) {
        if (!ctx.dryRun) source.files[rel] = newHash;
        result.added.push(proj);
      } else if (ctx.force) {
        if (!ctx.dryRun) {
          writeFileEnsuringDir(abs, newBuf);
          source.files[rel] = newHash;
        }
        result.forced.push(proj);
      } else {
        result.skipped.push({ path: proj, reason: "new upstream file collides with an existing untracked file (re-run with --force to overwrite)" });
      }
      continue;
    }

    if (!inNew) {
      // Upstream deleted the file.
      if (diskHash === null) {
        if (!ctx.dryRun) delete source.files[rel];
        result.deleted.push(proj);
      } else if (diskHash === stored) {
        if (!ctx.dryRun) {
          rmSync(abs);
          pruneEmptyDirs(root, dirname(proj));
          delete source.files[rel];
        }
        result.deleted.push(proj);
      } else {
        result.warnings.push({ path: proj, message: "upstream deleted this file but it has local modifications; kept the local copy" });
      }
      continue;
    }

    const oldBuf = oldSet.has(rel) ? readFileAt(cache, oldSha, upstreamPath(source.path, rel)) : null;
    const oldHash = oldBuf === null ? null : sha256(oldBuf);

    if (oldHash === newHash) {
      // Upstream unchanged for this file: leave local state alone.
      continue;
    }
    if (newBuf === null || newHash === null) continue;

    if (diskHash === null) {
      result.warnings.push({ path: proj, message: "deleted locally but changed upstream; left deleted (copy from upstream manually if wanted)" });
      continue;
    }

    if (diskHash === stored) {
      // No local edits: fast-forward to upstream.
      if (!ctx.dryRun) {
        writeFileEnsuringDir(abs, newBuf);
        source.files[rel] = newHash;
      }
      result.fastForwarded.push(proj);
      continue;
    }

    if (diskHash === newHash) {
      // Disk already matches new upstream (e.g. manually updated).
      if (!ctx.dryRun) source.files[rel] = newHash;
      result.fastForwarded.push(proj);
      continue;
    }

    // Local edits AND upstream changes: merge or conflict.
    const binary = isBinary(diskBuf as Buffer) || isBinary(newBuf) || (oldBuf !== null && isBinary(oldBuf));
    if (binary) {
      if (ctx.force) {
        if (!ctx.dryRun) {
          writeFileEnsuringDir(abs, newBuf);
          source.files[rel] = newHash;
        }
        result.forced.push(proj);
      } else {
        result.warnings.push({ path: proj, message: "binary file changed both locally and upstream; kept the local version (re-run with --force to take upstream)" });
      }
      continue;
    }

    const merged = mergeThreeWay({ base: oldBuf ?? Buffer.alloc(0), ours: diskBuf as Buffer, theirs: newBuf });
    if (!merged.conflicted) {
      if (!ctx.dryRun) {
        writeFileEnsuringDir(abs, merged.content);
        source.files[rel] = sha256(merged.content);
      }
      result.merged.push(proj);
    } else if (ctx.force) {
      if (!ctx.dryRun) {
        writeFileEnsuringDir(abs, newBuf);
        source.files[rel] = newHash;
      }
      result.forced.push(proj);
    } else {
      if (!ctx.dryRun) {
        writeFileEnsuringDir(abs, merged.content);
        source.unresolved.push(rel);
      }
      result.conflicts.push(proj);
    }
  }

  return result;
}
