import type { Intent } from "./manifest";
import { briefsDir, WORKDIR_NAME, writeFileEnsuringDir } from "./workspace";

export interface BriefWarning {
  path: string;
  message: string;
}

export interface BriefSection {
  graftId: string;
  graftName: string;
  url: string;
  remoteRef: string;
  oldSha: string;
  newSha: string;
  /** Project-root-relative paths with diff3 markers written in place. */
  conflicts: string[];
  /** Files needing attention that were NOT merged (binary conflicts, modified-but-deleted-upstream, ...). */
  warnings: BriefWarning[];
  /** Intent IDs currently active for affected files in this Graft. */
  activeIntentIds: string[];
  /** `git log --oneline old..new -- <path>` output. */
  log: string;
}

/** Filesystem-safe ISO timestamp (colons replaced with dashes). */
export function briefTimestamp(date: Date): string {
  return date.toISOString().replace(/:/g, "-");
}

function short(sha: string): string {
  return sha.slice(0, 7);
}

export function renderBrief(sections: BriefSection[], intents: readonly Intent[], generatedAt: Date): string {
  const affected = new Set<string>();
  for (const s of sections) {
    for (const c of s.conflicts) affected.add(c);
    for (const w of s.warnings) affected.add(w.path);
  }
  const activeIntentIds = new Set(sections.flatMap((section) => section.activeIntentIds));
  const relevantIntents = intents.filter((intent) => activeIntentIds.has(intent.id));

  const lines: string[] = [];
  lines.push(`# Regraft Brief — ${briefTimestamp(generatedAt)}`, "");
  lines.push(
    "Generated by `regraft pull` because an Update requires human or agent judgment.",
    "Regraft completed the deterministic work and preserved the context needed to decide the rest.",
    "",
  );

  for (const s of sections) {
    lines.push(`## Graft: ${s.graftName} (${s.graftId})`, "");
    lines.push(`Source: ${s.url} (${s.remoteRef})`, "");
    lines.push(`Pinned commit advanced: \`${short(s.oldSha)}\` → \`${short(s.newSha)}\``, "");
    if (s.conflicts.length > 0) {
      lines.push("### Conflicted files (diff3 markers written in place)", "");
      for (const c of s.conflicts) lines.push(`- \`${c}\``);
      lines.push("");
    }
    if (s.warnings.length > 0) {
      lines.push("### Warnings", "");
      for (const w of s.warnings) lines.push(`- \`${w.path}\`: ${w.message}`);
      lines.push("");
    }
    lines.push(`### Upstream commits (${short(s.oldSha)}..${short(s.newSha)})`, "");
    lines.push("```");
    lines.push(s.log || "(no commits touched this path)");
    lines.push("```", "");
  }

  lines.push("## Relevant local notes (full text, from PATCH.md)", "");
  if (relevantIntents.length === 0) {
    lines.push(
      "_No recorded note covers the affected files. The local changes below are",
      "UNRECORDED. Inspect the `local` side of each conflict to infer what they do,",
      "then record a note with `regraft note` once fixed._",
      "",
    );
  } else {
    for (const intent of relevantIntents) {
      lines.push(`### ${intent.date.slice(0, 10)} — ${intent.id}`, "");
      lines.push(
        `Files: ${intent.targets
          .filter((target) => affected.has(target.path))
          .map((target) => `\`${target.path}\``)
          .join(", ")}`,
        "",
      );
      lines.push(intent.description.trim(), "");
    }
  }

  lines.push("## Instructions for the person or agent fixing this", "");
  lines.push(
    "1. Open each conflicted file. Conflicts are marked inline in diff3 style:",
    "   `<<<<<<< local` (your customized version), `||||||| base` (the old upstream",
    "   version both sides started from), `>>>>>>> upstream` (the new upstream version).",
    "2. For every conflict, rebuild what each note above says the local change must",
    "   still do on top of the NEW upstream code. Do not blindly keep the local side.",
    "3. Handle each warning above (binary conflicts and upstream deletions must be",
    "   decided manually: keep local, take upstream, or delete).",
    "4. Remove ALL conflict markers from every file.",
    '5. Run `regraft resolve --note "<how the conflicts were fixed>"`.',
    "6. Verify with `regraft status` (it must exit 0, ignoring staleness of other sources).",
    "",
  );
  return lines.join("\n");
}

/** Write the brief; returns its project-root-relative path. */
export function writeBrief(root: string, content: string, generatedAt: Date): string {
  briefsDir(root);
  const file = `${WORKDIR_NAME}/briefs/${briefTimestamp(generatedAt)}.md`;
  writeFileEnsuringDir(root, file, content);
  return file;
}
