import { mkdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { Intent } from "./manifest";
import { briefsDir } from "./workspace";

export interface BriefWarning {
  path: string;
  message: string;
}

export interface BriefSection {
  url: string;
  remoteRef: string;
  oldSha: string;
  newSha: string;
  /** Project-root-relative paths with diff3 markers written in place. */
  conflicts: string[];
  /** Files needing attention that were NOT merged (binary conflicts, modified-but-deleted-upstream, ...). */
  warnings: BriefWarning[];
  /** `git log --oneline old..new -- <path>` output. */
  log: string;
}

/** Filesystem-safe ISO timestamp (colons replaced with dashes). */
export function briefTimestamp(date: Date): string {
  return date.toISOString().replace(/:/g, "-");
}

function short(sha: string): string {
  return sha.slice(0, 7);
}

export function renderBrief(sections: BriefSection[], intents: readonly Intent[], generatedAt: Date): string {
  const affected = new Set<string>();
  for (const s of sections) {
    for (const c of s.conflicts) affected.add(c);
    for (const w of s.warnings) affected.add(w.path);
  }
  const relevantIntents = intents.filter((i) => Object.keys(i.files).some((p) => affected.has(p)));

  const lines: string[] = [];
  lines.push(`# regraft conflict brief — ${briefTimestamp(generatedAt)}`, "");
  lines.push(
    "Generated by `regraft pull` because upstream changes did not merge cleanly",
    "with your local changes. This brief contains what you need to fix them.",
    "",
  );

  for (const s of sections) {
    lines.push(`## Source: ${s.url} (${s.remoteRef})`, "");
    lines.push(`Pinned commit advanced: \`${short(s.oldSha)}\` → \`${short(s.newSha)}\``, "");
    if (s.conflicts.length > 0) {
      lines.push("### Conflicted files (diff3 markers written in place)", "");
      for (const c of s.conflicts) lines.push(`- \`${c}\``);
      lines.push("");
    }
    if (s.warnings.length > 0) {
      lines.push("### Warnings", "");
      for (const w of s.warnings) lines.push(`- \`${w.path}\`: ${w.message}`);
      lines.push("");
    }
    lines.push(`### Upstream commits (${short(s.oldSha)}..${short(s.newSha)})`, "");
    lines.push("```");
    lines.push(s.log || "(no commits touched this path)");
    lines.push("```", "");
  }

  lines.push("## Relevant local notes (full text, from PATCH.md)", "");
  if (relevantIntents.length === 0) {
    lines.push(
      "_No recorded note covers the affected files. The local changes below are",
      "UNRECORDED. Inspect the `local` side of each conflict to infer what they do,",
      "then record a note with `regraft note` once fixed._",
      "",
    );
  } else {
    for (const intent of relevantIntents) {
      lines.push(`### ${intent.date.slice(0, 10)} — ${intent.id}`, "");
      lines.push(`Files: ${Object.keys(intent.files).map((p) => `\`${p}\``).join(", ")}`, "");
      lines.push(intent.description.trim(), "");
    }
  }

  lines.push("## Instructions for the person or agent fixing this", "");
  lines.push(
    "1. Open each conflicted file. Conflicts are marked inline in diff3 style:",
    "   `<<<<<<< local` (your customized version), `||||||| base` (the old upstream",
    "   version both sides started from), `>>>>>>> upstream` (the new upstream version).",
    "2. For every conflict, rebuild what each note above says the local change must",
    "   still do on top of the NEW upstream code. Do not blindly keep the local side.",
    "3. Handle each warning above (binary conflicts and upstream deletions must be",
    "   decided manually: keep local, take upstream, or delete).",
    "4. Remove ALL conflict markers from every file.",
    '5. Run `regraft resolve --note "<how the conflicts were fixed>"`.',
    "6. Verify with `regraft status` (it must exit 0, ignoring staleness of other sources).",
    "",
  );
  return lines.join("\n");
}

/** Write the brief; returns its project-root-relative path. */
export function writeBrief(root: string, content: string, generatedAt: Date): string {
  const dir = briefsDir(root);
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `${briefTimestamp(generatedAt)}.md`);
  writeFileSync(file, content);
  return relative(root, file);
}
