import type { Manifest } from "./manifest";
import { projectPath, writeFileAtomic } from "./workspace";

export const PATCH_MD_FILE = "PATCH.md";

/** All project-root-relative paths currently tracked by any source. */
export function trackedProjectPaths(manifest: Manifest): Set<string> {
  const set = new Set<string>();
  for (const graft of manifest.grafts) {
    for (const rel of Object.keys(graft.files)) set.add(projectPath(graft.dest, rel));
  }
  return set;
}

const HEADER = `# PATCH.md — Intent for Regraft Grafts

<!-- Generated by regraft. Do not edit by hand; run \`regraft note\` to add entries. -->

This file records why Grafts intentionally differ from their Sources. Each entry
captures what changed and, more importantly, **why**.
When \`regraft pull\` hits a conflict, the person or agent fixing it reads these
notes to rebuild the change on top of the new upstream code, matching its purpose
instead of blindly keeping the old diff.

Entries marked *orphaned* refer to files that are no longer tracked; they are kept
as history.
`;

export function renderPatchMd(manifest: Manifest): string {
  const lines: string[] = [HEADER];
  if (manifest.intents.length === 0) {
    lines.push(
      '_No notes recorded yet. After changing a tracked file, run `regraft note "<what and why>"`._',
      "",
    );
    return lines.join("\n");
  }
  const isActive = (intentId: string, target: Manifest["intents"][number]["targets"][number]): boolean => {
    if (target.kind === "legacy-orphan") return false;
    const graft = manifest.grafts.find((candidate) => candidate.id === target.graftId);
    const file = graft?.files[target.rel];
    return Boolean(
      graft &&
        file &&
        projectPath(graft.dest, target.rel) === target.path &&
        file.intentIds.includes(intentId),
    );
  };
  for (const intent of manifest.intents) {
    const orphaned = intent.targets.every((target) => !isActive(intent.id, target));
    const suffix = orphaned ? " (orphaned — files no longer tracked)" : "";
    lines.push(`## ${intent.date.slice(0, 10)} — ${intent.id}${suffix}`, "");
    lines.push("Files:");
    for (const target of intent.targets) {
      const note = isActive(intent.id, target) ? "" : " *(inactive or untracked)*";
      const hash = target.hash === null ? "deleted" : target.hash.slice(0, 12);
      const graft =
        target.kind === "graft-file"
          ? ` · Graft \`${manifest.grafts.find((candidate) => candidate.id === target.graftId)?.name ?? target.graftId}\``
          : "";
      lines.push(`- \`${target.path}\` @ \`${hash}\`${graft}${note}`);
    }
    lines.push("", intent.description.trim(), "");
  }
  return lines.join("\n");
}

export function writePatchMd(root: string, manifest: Manifest): void {
  writeFileAtomic(root, PATCH_MD_FILE, renderPatchMd(manifest));
}
