import type { Manifest } from "./manifest";
import { projectPath, writeFileEnsuringDir } from "./workspace";

export const PATCH_MD_FILE = "PATCH.md";

/** All project-root-relative paths currently tracked by any source. */
export function trackedProjectPaths(manifest: Manifest): Set<string> {
  const set = new Set<string>();
  for (const source of manifest.sources) {
    for (const rel of Object.keys(source.files)) set.add(projectPath(source.dest, rel));
  }
  return set;
}

const HEADER = `# PATCH.md — local notes for copied code

<!-- Generated by regraft. Do not edit by hand; run \`regraft note\` to add entries. -->

This file is the note journal for copied code. It explains why your copy differs
from upstream. Each entry records what changed and, more importantly, **why**.
When \`regraft pull\` hits a conflict, the person or agent fixing it reads these
notes to rebuild the change on top of the new upstream code, matching its purpose
instead of blindly keeping the old diff.

Entries marked *orphaned* refer to files that are no longer tracked; they are kept
as history.
`;

export function renderPatchMd(manifest: Manifest): string {
  const lines: string[] = [HEADER];
  if (manifest.intents.length === 0) {
    lines.push(
      '_No notes recorded yet. After changing a tracked file, run `regraft note "<what and why>"`._',
      "",
    );
    return lines.join("\n");
  }
  const tracked = trackedProjectPaths(manifest);
  for (const intent of manifest.intents) {
    const orphaned = Object.keys(intent.files).every((p) => !tracked.has(p));
    const suffix = orphaned ? " (orphaned — files no longer tracked)" : "";
    lines.push(`## ${intent.date.slice(0, 10)} — ${intent.id}${suffix}`, "");
    lines.push("Files:");
    for (const [path, hash] of Object.entries(intent.files)) {
      const note = tracked.has(path) ? "" : " *(untracked)*";
      lines.push(`- \`${path}\` @ \`${hash.slice(0, 12)}\`${note}`);
    }
    lines.push("", intent.description.trim(), "");
  }
  return lines.join("\n");
}

export function writePatchMd(root: string, manifest: Manifest): void {
  writeFileEnsuringDir(root, PATCH_MD_FILE, renderPatchMd(manifest));
}
